# Generated by Django 5.2 on 2026-07-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sueldo mensual fijo del empleado', max_digits=10),
        ),
    ]
