# Generated by Django 5.2 on 2026-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='payments/vouchers/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('PAYPHONE', 'PayPhone'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('DEUNA', 'DE UNA'), ('CASH', 'Efectivo')], max_length=10),
        ),
    ]
