# Generated by Django 5.2 on 2026-07-13 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0006_alter_branchschedule_options_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('MOTORIZADO', 'Motorizado / entregas'), ('PUBLICIDAD', 'Publicidad y marketing'), ('ONLINE', 'Gastos en linea'), ('ALIMENTACION', 'Alimentacion'), ('SERVICIOS', 'Servicios'), ('INSUMOS', 'Insumos / limpieza'), ('NOMINA', 'Nomina'), ('OTROS', 'Otros')], default='OTROS', max_length=16)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('receipt_url', models.URLField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='expenses_ex_tenant__6b7e91_idx'), models.Index(fields=['tenant', 'category'], name='expenses_ex_tenant__ff6300_idx')],
            },
        ),
    ]
