# Generated by Django 5.2 on 2026-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='brand',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Aparece en la home'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_dark_url',
            field=models.URLField(blank=True, help_text='Logo para fondos oscuros'),
        ),
        migrations.AddField(
            model_name='brand',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant', 'is_active'], name='brands_bran_tenant__909dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant', 'is_featured'], name='brands_bran_tenant__5d4f5e_idx'),
        ),
    ]
