# Generated by Django 5.2 on 2026-06-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=160)),
                ('smtp_password', models.CharField(blank=True, max_length=240)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.EmailField(default='no-reply@delux.local', max_length=254)),
                ('default_from_name', models.CharField(default='Delux', max_length=120)),
                ('support_email', models.EmailField(blank=True, default='soporte@delux.local', max_length=254)),
                ('activation_code_ttl_minutes', models.PositiveIntegerField(default=15)),
                ('password_reset_ttl_minutes', models.PositiveIntegerField(default=30)),
                ('platform_name', models.CharField(default='Delux', max_length=120)),
                ('platform_tagline', models.CharField(blank=True, default='Sneakers, Ropa y mas', max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de plataforma',
                'verbose_name_plural': 'Configuracion de plataforma',
            },
        ),
    ]
