# Generated by Django 5.2 on 2026-06-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0005_platformsettings_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=15, help_text='IVA %% aplicado al precio de venta para mostrar el precio final.', max_digits=5),
        ),
    ]
