# Generated by Django 5.2 on 2026-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0007_affiliate_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='affiliate_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='%% de comision global para vendedores afiliados.', max_digits=5),
        ),
    ]
