# Generated by Django 5.2 on 2026-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0008_alter_platformsettings_affiliate_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='affiliate_min_payout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto minimo de comisiones acumuladas para poder registrar un pago (0 = sin minimo).', max_digits=10),
        ),
    ]
