# Generated by Django 5.2 on 2026-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0009_platformsettings_affiliate_min_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='bank_account_document',
            field=models.CharField(blank=True, default='', help_text='Cédula/RUC del titular (opcional).', max_length=40),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_account_type',
            field=models.CharField(blank=True, default='', help_text='Ahorros / Corriente', max_length=40),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_contact_whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='deuna_enabled',
            field=models.BooleanField(default=False, help_text='Habilita el pago con DE UNA (QR) en el checkout.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='deuna_instructions',
            field=models.TextField(blank=True, default='', help_text='Instrucciones que ve el cliente al pagar con DE UNA.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='deuna_qr',
            field=models.ImageField(blank=True, null=True, upload_to='platform/deuna/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='transfer_enabled',
            field=models.BooleanField(default=True, help_text='Habilita el pago por transferencia bancaria en el checkout.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='transfer_instructions',
            field=models.TextField(blank=True, default='', help_text='Instrucciones que ve el cliente al pagar por transferencia.'),
        ),
    ]
