# Generated by Django 5.2 on 2026-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0010_platformsettings_bank_account_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='public_contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email de contacto que se muestra en la web (si vacío usa support_email).', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_telegram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_tiktok',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_x',
            field=models.URLField(blank=True, default='', help_text='X (antes Twitter).'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
