# Generated by Django 5.2 on 2026-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0012_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='recaptcha_enabled',
            field=models.BooleanField(default=False, help_text='Activa/desactiva el reCAPTCHA en todos los formularios públicos.'),
        ),
    ]
