# Generated by Django 5.2 on 2026-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0015_consumidor_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_api_key',
            field=models.CharField(blank=True, default='', help_text='API key de NovaFactura (Authorization: Api-Key ...). Secreta.', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_base_url',
            field=models.URLField(blank=True, default='', help_text='URL base de la API de NovaFactura, ej. https://api.novafactura.com'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_branch_uuid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_company_uuid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_emission_point_uuid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, cada venta pagada intenta emitir factura electrónica en NovaFactura.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_environment',
            field=models.CharField(choices=[('pruebas', 'Pruebas (sandbox SRI)'), ('produccion', 'Producción')], default='pruebas', max_length=12),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Secreto compartido para verificar (HMAC) los webhooks de NovaFactura.', max_length=200),
        ),
    ]
