# Generated by Django 5.2 on 2026-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0016_platformsettings_einvoice_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='einvoice_consumidor_final_max',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Monto máximo permitido para facturar como Consumidor Final. Ventas de este valor o más exigen cédula/RUC del cliente (regla SRI).', max_digits=10),
        ),
    ]
