# Generated by Django 5.2 on 2026-06-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_isfeatured'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_tenant__a2f2ca_idx',
            old_name='products_pr_tenant__d6d1ce_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_brand_i_98ddd0_idx',
            old_name='products_pr_brand_i_a5e9bf_idx',
        ),
    ]
