# Generated by Django 5.2 on 2026-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_pr_tenant__d6d1ce_idx_products_pr_tenant__a2f2ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
    ]
