# Generated by Django 5.2 on 2026-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA %% de este producto. Vacio = usa el IVA global de Configuracion.', max_digits=5, null=True),
        ),
    ]
