# Generated by Django 5.2 on 2026-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
