# Generated by Django 5.2 on 2026-07-02 17:08

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_dedupe_and_unique_email'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('tenant'), condition=models.Q(('email', ''), _negated=True), name='uniq_customer_tenant_email'),
        ),
    ]
