# Generated by Django 5.2 on 2026-08-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_invoice_message_and_more'),
        ('returns', '0003_salechange'),
        ('tenants', '0001_initial'),
        ('variants', '0004_variant_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salechange',
            name='delivered_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salechange',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salechange',
            name='returned_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SaleChangeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('RETURN', 'Devuelto'), ('DELIVER', 'Entregado')], max_length=8)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('sku', models.CharField(blank=True, default='', max_length=40)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.salechange')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_lines', to='orders.orderitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='variants.variant')),
            ],
            options={
                'ordering': ['direction', 'id'],
            },
        ),
    ]
