# Generated by Django 5.2 on 2026-08-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
        ('returns', '0005_salechange_annulled_salechange_annulled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salechange',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_changes', to='cashbox.cashsession'),
        ),
        migrations.AddField(
            model_name='salechange',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='salechange',
            name='tipo',
            field=models.CharField(choices=[('PARCIAL', 'Cambio parcial'), ('TOTAL', 'Cambio total'), ('REFUND', 'Devolución de dinero')], default='PARCIAL', max_length=8),
        ),
    ]
