# Generated by Django 5.2 on 2026-08-31 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_branch_province'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant')),
            ],
            options={
                'ordering': ['branch__name', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], db_index=True, default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_note', models.CharField(blank=True, default='', max_length=300)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_note', models.CharField(blank=True, default='', max_length=300)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_in', models.DecimalField(decimal_places=2, default=0, help_text='Diferencias de cambios que el cliente pagó (entra efectivo).', max_digits=12)),
                ('change_out', models.DecimalField(decimal_places=2, default=0, help_text='Diferencias de cambios devueltas al cliente (sale efectivo).', max_digits=12)),
                ('expenses_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cashbox.cashregister')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Retiro')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cashbox.cashsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('OPENING', 'Apertura'), ('CLOSING', 'Cierre')], max_length=8)),
                ('piece', models.CharField(choices=[('BILL', 'Billete'), ('COIN', 'Moneda')], default='BILL', max_length=4)),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='cashbox.cashsession')),
            ],
            options={
                'ordering': ['stage', 'piece', '-denomination'],
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['tenant', 'status'], name='cashbox_cas_tenant__f3d6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='cashbox_cas_tenant__0551bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('register',), name='unique_open_session_per_register'),
        ),
        migrations.AlterUniqueTogether(
            name='cashcountline',
            unique_together={('session', 'stage', 'piece', 'denomination')},
        ),
    ]
