# Generated by Django 5.2 on 2026-07-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_payout'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commission',
            new_name='affiliates__tenant__9f4092_idx',
            old_name='affiliates__tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='commissionpayout',
            new_name='affiliates__tenant__753f8f_idx',
            old_name='affiliates__tenant__po_idx',
        ),
        migrations.AlterField(
            model_name='commission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='commissionpayout',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', related_query_name='%(class)s', to='tenants.tenant'),
        ),
    ]
