# Generated by Django 5.2 on 2026-07-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_latlon_precision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchschedule',
            options={},
        ),
        migrations.AddField(
            model_name='branch',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
