# Generated by Django 5.2 on 2026-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branchschedule_options_branch_free_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchschedule',
            options={'ordering': ['branch', 'weekday']},
        ),
        migrations.AddField(
            model_name='branch',
            name='free_shipping_label',
            field=models.CharField(blank=True, default='Envío a domicilio gratis', max_length=120),
        ),
    ]
