# Generated by Django 5.2 on 2026-06-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchschedule'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sucursal desde la que se reserva/despacha este ítem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='branches.branch'),
        ),
    ]
