# Generated by Django 5.2 on 2026-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_access_key',
            field=models.CharField(blank=True, default='', help_text='Clave de acceso del SRI.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_error',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, default='', help_text='ID de la factura en NovaFactura.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_ISSUED', 'No emitida'), ('PROCESSING', 'Procesando'), ('AUTHORIZED', 'Autorizada'), ('REJECTED', 'Rechazada'), ('ERROR', 'Error')], db_index=True, default='NOT_ISSUED', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_xml_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
