# Generated by Django 5.2 on 2026-08-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
        ('orders', '0009_order_invoice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cashbox.cashsession'),
        ),
    ]
