# Generated by Django 5.2 on 2026-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_clear_price_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
